import{apiSlice}from"@/store/apiSlice";import type{ApiResponse}from"@/types/api";import type{CreateFuelLogRequest,CreateMaintenanceLogRequest,CreateVehicleRequest,DepartmentSummary,Vehicle,VehicleFuelLog,VehicleMaintenanceLog,VehiclesResponse}from"./types";
export type VehicleOption=Vehicle;
const expense=[{type:"Expense" as const,id:"LIST"}];
export const vehiclesApi=apiSlice.injectEndpoints({endpoints:(builder)=>({
listVehicles:builder.query<VehiclesResponse,{departmentId?:string;page?:number;limit?:number}|void>({query:(params)=>({url:"/api/v1/vehicles",params:params?Object.fromEntries(Object.entries(params).filter(([,v])=>v!==undefined&&v!=="")):undefined}),providesTags:(result)=>[{type:"Vehicle",id:"LIST"},...(result?.data.items.map(({id})=>({type:"Vehicle" as const,id}))??[])]}),
getVehicle:builder.query<ApiResponse<Vehicle>,string>({query:(id)=>`/api/v1/vehicles/${id}`,providesTags:(_r,_e,id)=>[{type:"Vehicle",id}]}),
createVehicle:builder.mutation<ApiResponse<Vehicle>,CreateVehicleRequest>({query:(body)=>({url:"/api/v1/vehicles",method:"POST",body}),invalidatesTags:[{type:"Vehicle",id:"LIST"}]}),
updateVehicle:builder.mutation<ApiResponse<Vehicle>,{id:string;body:Partial<CreateVehicleRequest>}>({query:({id,body})=>({url:`/api/v1/vehicles/${id}`,method:"PATCH",body}),invalidatesTags:(_r,_e,{id})=>[{type:"Vehicle",id},{type:"Vehicle",id:"LIST"}]}),
deleteVehicle:builder.mutation<ApiResponse<void>,string>({query:(id)=>({url:`/api/v1/vehicles/${id}`,method:"DELETE"}),invalidatesTags:(_r,_e,id)=>[{type:"Vehicle",id},{type:"Vehicle",id:"LIST"}]}),
listFuelLogs:builder.query<ApiResponse<VehicleFuelLog[]>,string>({query:(id)=>`/api/v1/vehicles/${id}/fuel-logs`,providesTags:(_r,_e,id)=>[{type:"VehicleFuelLog",id}]}),
createFuelLog:builder.mutation<ApiResponse<VehicleFuelLog>,{vehicleId:string;body:CreateFuelLogRequest}>({query:({vehicleId,body})=>({url:`/api/v1/vehicles/${vehicleId}/fuel-logs`,method:"POST",body}),invalidatesTags:(_r,_e,{vehicleId})=>[{type:"VehicleFuelLog",id:vehicleId},...expense]}),
updateFuelLog:builder.mutation<ApiResponse<VehicleFuelLog>,{id:string;vehicleId:string;body:Partial<CreateFuelLogRequest>}>({query:({id,body})=>({url:`/api/v1/vehicles/fuel-logs/${id}`,method:"PATCH",body}),invalidatesTags:(_r,_e,{vehicleId})=>[{type:"VehicleFuelLog",id:vehicleId},...expense]}),
deleteFuelLog:builder.mutation<ApiResponse<void>,{id:string;vehicleId:string}>({query:({id})=>({url:`/api/v1/vehicles/fuel-logs/${id}`,method:"DELETE"}),invalidatesTags:(_r,_e,{vehicleId})=>[{type:"VehicleFuelLog",id:vehicleId},...expense]}),
listMaintenanceLogs:builder.query<ApiResponse<VehicleMaintenanceLog[]>,string>({query:(id)=>`/api/v1/vehicles/${id}/maintenance-logs`,providesTags:(_r,_e,id)=>[{type:"VehicleMaintenanceLog",id}]}),
createMaintenanceLog:builder.mutation<ApiResponse<VehicleMaintenanceLog>,{vehicleId:string;body:CreateMaintenanceLogRequest}>({query:({vehicleId,body})=>({url:`/api/v1/vehicles/${vehicleId}/maintenance-logs`,method:"POST",body}),invalidatesTags:(_r,_e,{vehicleId})=>[{type:"VehicleMaintenanceLog",id:vehicleId},...expense]}),
updateMaintenanceLog:builder.mutation<ApiResponse<VehicleMaintenanceLog>,{id:string;vehicleId:string;body:Partial<CreateMaintenanceLogRequest>}>({query:({id,body})=>({url:`/api/v1/vehicles/maintenance-logs/${id}`,method:"PATCH",body}),invalidatesTags:(_r,_e,{vehicleId})=>[{type:"VehicleMaintenanceLog",id:vehicleId},...expense]}),
deleteMaintenanceLog:builder.mutation<ApiResponse<void>,{id:string;vehicleId:string}>({query:({id})=>({url:`/api/v1/vehicles/maintenance-logs/${id}`,method:"DELETE"}),invalidatesTags:(_r,_e,{vehicleId})=>[{type:"VehicleMaintenanceLog",id:vehicleId},...expense]}),
listDepartments:builder.query<ApiResponse<DepartmentSummary[]>,void>({query:()=>"/departments"}),
})});
export const{useListVehiclesQuery,useGetVehicleQuery,useCreateVehicleMutation,useUpdateVehicleMutation,useDeleteVehicleMutation,useListFuelLogsQuery,useCreateFuelLogMutation,useUpdateFuelLogMutation,useDeleteFuelLogMutation,useListMaintenanceLogsQuery,useCreateMaintenanceLogMutation,useUpdateMaintenanceLogMutation,useDeleteMaintenanceLogMutation,useListDepartmentsQuery}=vehiclesApi;
